server:
  port: 9100

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:9000/eureka/
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"